version: "3"

services:
  server:

    build: server/

    command: python ./image_processing.py

    ports:
      - 8000:5000
    volumes:
      - /usr/src/app
      - /usr/src/app/static

  client:

    build: client/

    command: python ./receive_return.py

    network_mode: host

    depends_on:
      - server

  rabbitmq:
    image: "rabbitmq:3-alpine"
    container_name: rabbitmq
    ports:
      - 5671:5671


  postgres:
    image: "postgres:12.0-alpine"
    environment:
      - POSTGRES_USER=kamil3
      - POSTGRES_PASSWORD=adsladsl199812
      - POSTGRES_DB=gino2
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5431:5432
